### ISSUE TITLE
Help finding documentation on Hetzner-specific API

### ISSUE THREAD

**Issue by jwoudenberg** [NixOS/nixops-hetzner#44]
I'm sorry if I just missed something completely obvious. I'd like to try out nixops on Hetzner, but have trouble finding documentation / example on how to use this plugin. I tried the links in the README.md on this project but they seem to lead to generic nixops documentation. There I find some information about configuring environmental variables the plugin needs to talk to Hetzner, but I don't see the API that makes use of these environment variables. I'd deeply appreciate any tips that would help me get going!

**Comment by RaghavSood** [comment]
The plugin in its current state cannot be used with nixops master

nixops 1.7 (what you get when installing nixops in nix 20.03) doesn't use the plugin system, but comes with the hetzner plugin built in.

You still need to patch it to use `cryptsetup` instead of `cryptsetup0` since cryptsetup0 is currently broken on at least 20.03.

You can also apply the patch from the zfs branch if you want ZFS support

**Comment by jwoudenberg** [comment]
Thank you for the pointers, appreciate it. Looks like I'm in the wrong place here!
